### ISSUE TITLE
What I had to do to get this to run

### ISSUE THREAD

**Issue by jfabiani** [codingjq/flet-firebase-tutorial#1]
Using Python 3.10.x (venv project), on Ubuntu 22.04:
The issue - I was getting an error collections does not have Mapping.  Of course it needed "collections.abc" and not collections.
On my venv I had to upgrade Urllib3 to the latest version.  Also I first started with pip install pyrebase which I later realized I needed pyrebase4.
Thanks for providing the code.

Johnf

**Comment by codingjq** [comment]
@jfabiani sorry I didn't explicitly point out that pyrebase exists and that pyrebase4 is the one to go with. I actually ran into the same problem in an earlier project when experimenting with pyrebase. Thanks for checking out the code! Have fun building.
