### ISSUE TITLE
Multiple value assignment to variables in register_view.py

### ISSUE THREAD

**Issue by Jose427** [codingjq/flet-firebase-tutorial#2]
Hi,

In register_view.py the code in line number 9 is: 
name, username, email, password = ''

It must be 
name, username, email, password = '', '', '', ''

because i received "Something's wrong. Please Try Again"

Greetings

**Comment by codingjq** [comment]
Looks like a solid improvement to me. I'll push it.

**Comment by codingjq** [comment]
Closed thanks, @Jose427. Feel free to make it a pull request next time so it shows up as a contribution on your profile!

**Comment by Jose427** [comment]
Thanks. I'm "new" to this
